Extracting HTML code from any website

Program flow
1.Import libraries

2.Save the URL

3.Using requests get(),access the web page

4.Using BeautifulSoup(),access the HTML code

In [ ]:
from bs4 import BeautifulSoup
import requests

In [ ]:
URL="https://colab.research.google.com/drive/1vVk7gcw9XCx37FTSmxubDGBlgdBlrWB3"
page=req.get(URL)
code=BeautifulSoup(page.text,'html')
print(code)

In [ ]:
t=code.find('title')
print(t)

<title>Google Colab</title>

In [ ]:
print(t.text)

Google Colab

Extracting table from webpage

In [ ]:
u="https://www.forbesindia.com/article/explainers/top-10-richest-people-india/85909/1"
p=req.get(u)
c=BeautifulSoup(p.text,'html')
print(c)

In [ ]:
a=c.find("table")
a

In [ ]:
h=a.find_all('th')
h

In [ ]:
heading=[i.text for i in h]
heading

['Name & India Rank', 'Global Rank', 'Net worth (US$)', 'Company']

In [ ]:
import pandas as pd

In [ ]:
mydf=pd.DataFrame(columns=heading)
print(mydf)

NameError: name 'heading' is not defined

In [ ]:
rows=a.find_all("tr")
rows

In [ ]:
data=a.find_all("td")
data

[<td style="border: 1px solid black; padding: 8px;">#1 Mukesh Ambani <br/></td>,
 <td style="border: 1px solid black; padding: 8px;">10</td>,
 <td style="border: 1px solid black; padding: 8px;">$116.9 B</td>,
 <td style="border: 1px solid black; padding: 8px;">Reliance Industries</td>,
 <td style="border: 1px solid black; padding: 8px;">#2 Gautam Adani <br/></td>,
 <td style="border: 1px solid black; padding: 8px;">16<br/></td>,
 <td style="border: 1px solid black; padding: 8px;">$86.2 B</td>,
 <td style="border: 1px solid black; padding: 8px;">Adani Group</td>,
 <td style="border: 1px solid black; padding: 8px;">#3 Shiv Nadar <br/></td>,
 <td style="border: 1px solid black; padding: 8px;">37<br/></td>,
 <td style="border: 1px solid black; padding: 8px;">$36.8 B</td>,
 <td style="border: 1px solid black; padding: 8px;">HCL Technologies   <br/></td>,
 <td style="border: 1px solid black; padding: 8px;">#4 Savitri Jindal &amp; family <br/></td>,
 <td style="border: 1px solid black; padding: 8px;">58<br/></td>,
 <td style="border: 1px solid black; padding: 8px;">$30.9 B</td>,
 <td style="border: 1px solid black; padding: 8px;">JSW Group<br/></td>,
 <td style="border: 1px solid black; padding: 8px;">#5 Dilip Shanghvi <br/></td>,
 <td style="border: 1px solid black; padding: 8px;">69<br/></td>,
 <td style="border: 1px solid black; padding: 8px;">$25.7 B</td>,
 <td style="border: 1px solid black; padding: 8px;">Sun Pharmaceutical Industries Ltd</td>,
 <td style="border: 1px solid black; padding: 8px;">#6 Cyrus Poonawalla <br/></td>,
 <td style="border: 1px solid black; padding: 8px;">68<br/></td>,
 <td style="border: 1px solid black; padding: 8px;">$24.2 B</td>,
 <td style="border: 1px solid black; padding: 8px;">Serum Institute of India<br/></td>,
 <td style="border: 1px solid black; padding: 8px;">#7 Kushal Pal Singh<br/></td>,
 <td style="border: 1px solid black; padding: 8px;">98<br/></td>,
 <td style="border: 1px solid black; padding: 8px;">$20.6 B</td>,
 <td style="border: 1px solid black; padding: 8px;">DLF Limited<br/></td>,
 <td style="border: 1px solid black; padding: 8px;">#8 Kumar Birla <br/></td>,
 <td style="border: 1px solid black; padding: 8px;">97<br/></td>,
 <td style="border: 1px solid black; padding: 8px;">$19.5 B</td>,
 <td style="border: 1px solid black; padding: 8px;">Aditya Birla Group<br/></td>,
 <td style="border: 1px solid black; padding: 8px;">#9 Ravi Jaipuria<br/></td>,
 <td style="border: 1px solid black; padding: 8px;">100</td>,
 <td style="border: 1px solid black; padding: 8px;">$17.4 B</td>,
 <td style="border: 1px solid black; padding: 8px;">RJ Corp, Varun Beverages <br/></td>,
 <td style="border: 1px solid black; padding: 8px;">#10 Radhakishan Damani <br/></td>,
 <td style="border: 1px solid black; padding: 8px;">101<br/></td>,
 <td style="border: 1px solid black; padding: 8px;">$17.2 B</td>,
 <td style="border: 1px solid black; padding: 8px;">DMart, Avenue Supermarts</td>]

In [ ]:
data_act=[i.text for i in data]
print(data_act)

['#1 Mukesh Ambani ', '10', '$116.9 B', 'Reliance Industries', '#2 Gautam Adani ', '16', '$86.2 B', 'Adani Group', '#3 Shiv Nadar ', '37', '$36.8 B', 'HCL Technologies\xa0\xa0 ', '#4 Savitri Jindal & family ', '58', '$30.9 B', 'JSW Group', '#5 Dilip Shanghvi ', '69', '$25.7 B', 'Sun Pharmaceutical Industries Ltd', '#6 Cyrus Poonawalla ', '68', '$24.2 B', 'Serum Institute of India', '#7 Kushal Pal Singh', '98', '$20.6 B', 'DLF Limited', '#8 Kumar Birla ', '97', '$19.5 B', 'Aditya Birla Group', '#9 Ravi Jaipuria', '100', '$17.4 B', 'RJ Corp, Varun Beverages ', '#10 Radhakishan Damani ', '101', '$17.2 B', 'DMart, Avenue Supermarts']

In [ ]:
df1=pd.DataFrame(columns=['name','rank','nw','comp'])
df1

Empty DataFrame
Columns: [name, rank, nw, comp]
Index: []

In [ ]:
data_act[0:4]

['#1 Mukesh Ambani ', '10', '$116.9 B', 'Reliance Industries']

In [ ]:
ind=0
st=0
stop=4
for i in data_act:
  if stop<=40:
    df1.loc[ind]=data_act[st:stop]
    st=st+4
    stop=stop+4
    ind=ind+1
(df1)

,name,rank,nw,comp
0,#1 Mukesh Ambani,10,$116.9 B,Reliance Industries
1,#2 Gautam Adani,16,$86.2 B,Adani Group
2,#3 Shiv Nadar,37,$36.8 B,HCL Technologies
3,#4 Savitri Jindal & family,58,$30.9 B,JSW Group
4,#5 Dilip Shanghvi,69,$25.7 B,Sun Pharmaceutical Industries Ltd
5,#6 Cyrus Poonawalla,68,$24.2 B,Serum Institute of India
6,#7 Kushal Pal Singh,98,$20.6 B,DLF Limited
7,#8 Kumar Birla,97,$19.5 B,Aditya Birla Group
8,#9 Ravi Jaipuria,100,$17.4 B,"RJ Corp, Varun Beverages"
9,#10 Radhakishan Damani,101,$17.2 B,"DMart, Avenue Supermarts"

In [ ]:
mydf.to_csv("mydf.csv")

In [ ]:
from bs4 import BeautifulSoup
import requests

In [ ]:
d="https://en.m.wikipedia.org/wiki/List_of_tallest_buildings_in_India"
page=requests.get(d)
code=BeautifulSoup(page.text,'html')
code

In [ ]:
h=code.find('table')
h

In [ ]:
p=h.find_all('th')
p

[<th>Rank
 </th>,
 <th>Name
 </th>,
 <th>Image
 </th>,
 <th>City
 </th>,
 <th>Height
 </th>,
 <th>Floors
 </th>,
 <th>Year
 </th>,
 <th>Building type
 </th>,
 <th>Reference(s)
 </th>]

In [ ]:
headings=[i.text for i in p]
print(headings)

['Rank\n', 'Name\n', 'Image\n', 'City\n', 'Height\n', 'Floors\n', 'Year\n', 'Building type\n', 'Reference(s)\n']

In [ ]:
import pandas as pd

In [ ]:
df=pd.DataFrame(columns=headings)
(df)

Empty DataFrame
Columns: [Rank
, Name
, Image
, City
, Height
, Floors
, Year
, Building type
, Reference(s)
]
Index: []

In [ ]:
row_data=h.find_all('td')
row_data

In [ ]:
data_act1=[i.text for i in row_data]
print(data_act1)

['1\n', 'Palais Royale\n', '\xa0\n', 'Mumbai\n', '320 metres (1,050\xa0ft)\n', '88\n', '2018\n', 'Residential\n', '[22]', '2\n', 'Lokhandwala Minerva\n', '\xa0\n', 'Mumbai\n', '301 metres (988\xa0ft)\n', '78\n', '2023\n', 'Residential\n', '[23][24]', '3\n', 'Piramal Aranya Arav\n', '\n', 'Mumbai\n', '282.2 metres (926\xa0ft)\n', '83\n', '2022\n', 'Residential\n', '[25]', '4\n', 'World One\n', '\xa0\n', 'Mumbai\n', '280.2 metres (919\xa0ft)\n', '76\n', '2020\n', 'Residential\n', '[4][26]', '5\n', 'World View\n', '\xa0\n', 'Mumbai\n', '277.6 metres (911\xa0ft)\n', '73\n', '2020\n', 'Residential\n', '[27][28]', '6\n', 'Lodha Trump Tower\n', '\xa0\n', 'Mumbai\n', '268 metres (879\xa0ft)\n', '76\n', '2020\n', 'Residential\n', '[29][30][31]', 'Lodha Marquise\n', '\xa0\n', 'Lodha Allura\n', '\xa0\n', 'Lodha Parkside\n', '\xa0\n', 'Lodha Kiara\n', '\xa0\n', '11\n', 'Omkar 1973 Tower A\n', '\xa0\n', 'Mumbai\n', '267 metres (876\xa0ft)\n', '73\n', '2021\n', 'Residential\n', '[32][33]', 'Omkar 1973 Tower B\n', '\xa0\n', '13\n', 'Nathani Heights\n', '\xa0\n', 'Mumbai\n', '262 metres (860\xa0ft)\n', '72\n', '2020\n', 'Residential\n', '[34][35]', '14\n', 'Three Sixty West Tower B\n', '\xa0\n', 'Mumbai\n', '260 metres (853\xa0ft)\n', '66\n', '2021\n', 'Commercial\n', '[36][37]', '15\n', 'The 42\n', '\xa0\n', 'Kolkata\n', '260 metres (850\xa0ft)\n', '65\n', '2018\n', 'Residential\n', '[38][39][40]', '16\n', 'One Avighna Park\n', '\xa0\n', 'Mumbai\n', '260 metres (853\xa0ft)\n', '64\n', '2017\n', 'Residential\n', '[41][42][43]', '17\n', 'Rustomjee Crown Tower A\n', '\n', 'Mumbai\n', '259 metres (850\xa0ft)\n', '69\n', '2023\n', 'Residential\n', '[44][45][46]', 'Rustomjee Crown Tower B\n', '\n', '19\n', 'The Imperial I\n', '\xa0\n', 'Mumbai\n', '256 metres (840\xa0ft)\n', '60\n', '2010\n', 'Residential\n', '[47][48]', 'The Imperial II\n', '\xa0\n', '21\n', 'Three Sixty West Tower A\n', '\xa0\n', 'Mumbai\n', '255.6 metres (839\xa0ft)\n', '52\n', '2020\n', 'Commercial\n', '[49][50]', '22\n', 'Four Seasons Private Residences\n', '\xa0\n', 'Mumbai\n', '250 metres (820\xa0ft)\n', '55\n', '2022\n', 'Residential\n', '[51][52][53]', '23\n', 'Ahuja Towers\n', '\xa0\n', 'Mumbai\n', '250 metres (820\xa0ft)\n', '55\n', '2019\n', 'Residential\n', '[54][55]', '24\n', 'Crescent Bay Tower 6\n', '\n', 'Mumbai\n', '239.7 metres (786\xa0ft)\n', '62\n', '2019\n', 'Residential\n', '[56][57]', '25\n', 'Auris Serenity Tower 1\n', '\xa0\n', 'Mumbai\n', '235 metres (771\xa0ft)\n', '69\n', '2018\n', 'Residential\n', '[58][59][60]', 'Auris Serenity Tower 2\n', '\xa0\n', '2019\n', 'Auris Serenity Tower 3\n', '\xa0\n', '2021\n', '28\n', 'Salsette 27 Tower A\n', '\n', 'Mumbai\n', '225.2 metres (739\xa0ft)\n', '64\n', '2023\n', 'Residential\n', '[61][62]', 'Salsette 27 Tower B\n', '\n', '30\n', 'Indiabulls Sky Forest Tower 1\n', '\n', 'Mumbai\n', '225 metres (738\xa0ft)\n', '62\n', '2022\n', 'Residential\n', '[63][64]', 'Indiabulls Sky Forest Tower 2\n', '\n', '32\n', 'Two ICC\n', '\xa0\n', 'Mumbai\n', '223.2 metres (732\xa0ft)\n', '68\n', '2018\n', 'Residential\n', '[65][66][67]', '33\n', 'Crescent Bay Tower 5\n', '\n', 'Mumbai\n', '222.5 metres (730\xa0ft)\n', '63\n', '2019\n', 'Residential\n', '[68][57]', '34\n', 'World Crest\n', '\xa0\n', 'Mumbai\n', '222.5 metres (730\xa0ft)\n', '57\n', '2017\n', 'Residential\n', '[69][70]', '35\n', 'Lodha Bellissimo Tower 1\n', '\xa0\n', 'Mumbai\n', '222 metres (728\xa0ft)\n', '53\n', '2011\n', 'Residential\n', '[71][72][73]', 'Lodha Bellissimo Tower 2\n', '\xa0\n', '37\n', 'Indiabulls Sky Blu\n', '\xa0\n', 'Mumbai\n', '220 metres (722\xa0ft)\n', '56\n', '2019\n', 'Residential\n', '[74][75]', '38\n', 'Oberoi Sky City Tower A\n', '\xa0\n', 'Mumbai\n', '220 metres (722\xa0ft)\n', '67\n', '2021\n', 'Residential\n', '[76][77]', 'Oberoi Sky City Tower B\n', '\xa0\n', 'Oberoi Sky City Tower C\n', '\xa0\n', 'Oberoi Sky City Tower D\n', '\xa0\n', 'Oberoi Sky City Tower E\n', '\xa0\n', '43\n', 'Omkar Alta Monte Tower B\n', '\n', 'Mumbai\n', '218 metres (715\xa0ft)\n', '65\n', '2019\n', 'Residential\n', '[78][79][80]', '44\n', 'Century Mills Tower\n', '\n', 'Mumbai\n', '215.5 metres (707\xa0ft)\n', '51\n', '2014\n', 'Commercial\n', '[81][82]', '45\n', 'Raheja Imperia\n', '\n', 'Mumbai\n', '214 metres (702\xa0ft)\n', '52\n', '2020\n', 'Residential\n', '[83][84]', '46\n', 'Lodha Venezia A\n', '\n', 'Mumbai\n', '213.5 metres (700\xa0ft)\n', '68\n', '2017\n', 'Residential\n', '[85][86][87][88]', 'Lodha Venezia B\n', '\n', '2021\n', '48\n', 'Monte South Tower 1\n', '\n', 'Mumbai\n', '210 metres (689\xa0ft)\n', '60\n', '2022\n', 'Residential\n', '[89][90]', '49\n', 'Orchid Enclave\n', '\xa0\n', 'Mumbai\n', '210 metres (689\xa0ft)\n', '56\n', '2017\n', 'Residential\n', '[91][92]', '50\n', 'Orbit Terraces\n', '\n', 'Mumbai\n', '207 metres (679\xa0ft)\n', '61\n', '2021\n', 'Residential\n', '[93]', '51\n', 'Crescent Bay Tower 4\n', '\n', 'Mumbai\n', '206 metres (676\xa0ft)\n', '58\n', '2019\n', 'Residential\n', '[94][95][57]', '52\n', 'Kohinoor Square Tower A\n', '\xa0\n', 'Mumbai\n', '201.9 metres (662\xa0ft)\n', '50\n', '2019\n', 'Commercial\n', '[96][97]', '53\n', 'Celestia Spaces Tower A\n', '\n', 'Mumbai\n', '201 metres (659\xa0ft)\n', '59\n', '2022\n', 'Residential\n', '[98]', 'Celestia Spaces Tower B\n', '\n', '55\n', 'Oberoi Enigma Tower 1\n', '\n', 'Mumbai\n', '201 metres (659\xa0ft)\n', '58\n', '2023\n', 'Residential\n', '[99]', 'Oberoi Enigma Tower 2\n', '\n', '57\n', 'Kalpataru Avana\n', '\xa0\n', 'Mumbai\n', '201 metres (659\xa0ft)\n', '52\n', '2019\n', 'Residential\n', '[100][101]', '58\n', 'Crescent Bay Tower 3\n', '\n', 'Mumbai\n', '200 metres (656\xa0ft)\n', '56\n', '2022\n', 'Residential\n', '[102]', '59\n', 'Trump Tower Delhi NCR Tower 1\n', '\n', 'Gurugram\n', '200 metres (656\xa0ft)\n', '47\n', '2024\n', 'Commercial\n', '[103][104]', 'Trump Tower Delhi NCR Tower 2\n', '\n', '61\n', 'One ICC\n', '\xa0\n', 'Mumbai\n', '197.6 metres (648\xa0ft)\n', '61\n', '2018\n', 'Residential\n', '[105][106]', '62\n', 'Omkar Alta Monte Tower C\n', '\n', 'Mumbai\n', '197 metres (646\xa0ft)\n', '58\n', '2017\n', 'Residential\n', '[107]', '63\n', 'SD Alpine A\n', '\xa0\n', 'Mumbai\n', '196.5 metres (645\xa0ft)\n', '63\n', '2019[108]', 'Residential\n', '[109][108]', 'SD Alpine B\n', '\xa0\n', '65\n', 'Indiabulls Sky\n', '\xa0\n', 'Mumbai\n', '196 metres (643\xa0ft)\n', '48\n', '2016\n', 'Residential\n', '[110][111]', '66\n', 'Raheja Revanta\n', '\n', 'Gurugram\n', '195 metres (640\xa0ft)\n', '61\n', '2020\n', 'Residential\n', '[112][113][114]', '67\n', 'Raheja Tower\n', '\n', 'Mumbai\n', '195 metres (640\xa0ft)\n', '48\n', '2022\n', 'Residential\n', '[115]', '68\n', 'Lodha Altamount\n', '\xa0\n', 'Mumbai\n', '195 metres (640\xa0ft)\n', '43\n', '2018\n', 'Residential\n', '[116][117]', '69\n', 'Ariisto Sommet\n', '\n', 'Mumbai\n', '194 metres (636\xa0ft)\n', '50\n', '2018\n', 'Residential\n', '[118]', '70\n', 'Raheja Vivarea 1\n', '\n', 'Mumbai\n', '193.8 metres (636\xa0ft)\n', '42\n', '2012\n', 'Residential\n', '[119]', 'Raheja Vivarea 2\n', '\n', 'Raheja Vivarea 3\n', '\n', 'Raheja Vivarea 4\n', '\n', '2018\n', '74\n', 'Orchid Woods 1\n', '\xa0\n', 'Mumbai\n', '193 metres (633\xa0ft)\n', '58\n', '2012\n', 'Residential\n', '[120][121]', 'Orchid Woods 2\n', '\xa0\n', 'Orchid Woods 3\n', '\xa0\n', '77\n', 'Ashok Towers D\n', '\xa0\n', 'Mumbai\n', '193 metres (633\xa0ft)\n', '49\n', '2009\n', 'Residential\n', '[122][123][124]', '78\n', 'Piramal Aranya Avyan\n', '\n', 'Mumbai\n', '192.9 metres (633\xa0ft)\n', '52\n', '2022\n', 'Residential\n', '[125]', '79\n', 'The Ruby\n', '\xa0\n', 'Mumbai\n', '191 metres (627\xa0ft)\n', '40\n', '2011\n', 'Commercial\n', '[126][127]', '80\n', 'Lodha Primero\n', '\xa0\n', 'Mumbai\n', '190 metres (623\xa0ft)\n', '52\n', '2014\n', 'Residential\n', '[128][129][130]', '81\n', 'Runwal Bliss 3\n', '\n', 'Mumbai\n', '190 metres (623\xa0ft)\n', '52\n', '2022\n', 'Residential\n', '[131][132][133]', 'Runwal Bliss 4\n', '\n', 'Runwal Bliss 5\n', '\n', '84\n', 'Dhaval Sunrise\n', '\n', 'Mumbai\n', '190 meters (623\xa0ft)\n', '40\n', '2022\n', 'Residential\n']

In [ ]:
print(len(data_act1))

563

In [ ]:
ind=0
st=0
sp=9
for i in data_act1:
  if sp<=563:
    df.loc[ind]=data_act1[st:sp]
    st=st+9
    sp=sp+9
    ind=ind+1
df

,Rank\n,Name\n,Image\n,City\n,Height\n,Floors\n,Year\n,Building type\n,Reference(s)\n
0,1\n,Palais Royale\n,\n,Mumbai\n,"320 metres (1,050 ft)\n",88\n,2018\n,Residential\n,[22]
1,2\n,Lokhandwala Minerva\n,\n,Mumbai\n,301 metres (988 ft)\n,78\n,2023\n,Residential\n,[23][24]
2,3\n,Piramal Aranya Arav\n,\n,Mumbai\n,282.2 metres (926 ft)\n,83\n,2022\n,Residential\n,[25]
3,4\n,World One\n,\n,Mumbai\n,280.2 metres (919 ft)\n,76\n,2020\n,Residential\n,[4][26]
4,5\n,World View\n,\n,Mumbai\n,277.6 metres (911 ft)\n,73\n,2020\n,Residential\n,[27][28]
...,...,...,...,...,...,...,...,...,...
57,Residential\n,[122][123][124],78\n,Piramal Aranya Avyan\n,\n,Mumbai\n,192.9 metres (633 ft)\n,52\n,2022\n
58,Residential\n,[125],79\n,The Ruby\n,\n,Mumbai\n,191 metres (627 ft)\n,40\n,2011\n
59,Commercial\n,[126][127],80\n,Lodha Primero\n,\n,Mumbai\n,190 metres (623 ft)\n,52\n,2014\n
60,Residential\n,[128][129][130],81\n,Runwal Bliss 3\n,\n,Mumbai\n,190 metres (623 ft)\n,52\n,2022\n
61,Residential\n,[131][132][133],Runwal Bliss 4\n,\n,Runwal Bliss 5\n,\n,84\n,Dhaval Sunrise\n,\n

In [ ]:
df.to_csv("df.csv")